#!/usr/bin/env ruby

require 'bundler/setup'
require 'prawn'
require 'prawn/measurement_extensions'

FILE_NAME = 'proxies.pdf'

PAGE_SIZE = 'A4'
PAGE_WIDTH = 210.mm
PAGE_HEIGHT = 297.mm
CARD_WIDTH = 63.5.mm
CARD_HEIGHT = 88.9.mm
X_GAP = (PAGE_WIDTH - 3 * CARD_WIDTH) / 4
Y_GAP = (PAGE_HEIGHT - 3 * CARD_HEIGHT) / 4
CARDS_PER_PAGE = 9

cards = $stdin.each_line.map(&:strip)

def positions
  Enumerator.new do |out|
    CARDS_PER_PAGE.times do |n|
      x = X_GAP + (n % 3) * (CARD_WIDTH + X_GAP)
      y = PAGE_HEIGHT - Y_GAP - (n / 3) * (CARD_HEIGHT + Y_GAP)
      out << [x, y]
    end
  end
end

Prawn::Document.generate(
  FILE_NAME,
  margin: 0,
  print_scaling: :none,
  page_size: PAGE_SIZE
) do |pdf|
  p = nil
  cards.each.with_index do |card, i|
    if i % CARDS_PER_PAGE == 0
      p = positions
      pdf.start_new_page if i > 0
    end
    pdf.image(
      card,
      at: p.next,
      width: CARD_WIDTH,
      height: CARD_HEIGHT
    )
  end
end
