#!/usr/bin/env ruby

require 'bundler/setup'
require 'prawn'
require 'prawn/measurement_extensions'

card = '/home/helge/Documents/Netrunner/Cards/12 - Red Sand/06 - Crimson Dust/104 - Aumakua.jpg'
FILE_NAME = 'netrunner-proxies.pdf'

PAGE_SIZE = 'A4'
PAGE_WIDTH = 210.mm
PAGE_HEIGHT = 297.mm
CARD_WIDTH = 63.5.mm
CARD_HEIGHT = 88.9.mm
X_GAP = (PAGE_WIDTH - 3 * CARD_WIDTH) / 4
Y_GAP = (PAGE_HEIGHT - 3 * CARD_HEIGHT) / 4

def positions
  Enumerator.new do |out|
    9.times do |n|
      x = X_GAP + (n % 3) * (CARD_WIDTH + X_GAP)
      y = (n / 3 + 1) * (CARD_HEIGHT + Y_GAP)
      out << [x, y]
    end
  end
end

Prawn::Document.generate(
  FILE_NAME,
  margin: 0,
  print_scaling: :none,
  page_size: PAGE_SIZE
) do |pdf|
  p = positions
  9.times do
    pdf.image(
      card,
      at: p.next,
      width: CARD_WIDTH,
      height: CARD_HEIGHT
    )
  end
end
